name: Publish to Sonatype

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew jreleaserPublish \
            -DSONATYPE_USERNAME=$SONATYPE_USERNAME \
            -DSONATYPE_PASSWORD=$SONATYPE_PASSWORD \
            -DGPG_PUBLIC_KEY=$GPG_PUBLIC_KEY \
            -DGPG_SECRET_KEY=$GPG_SECRET_KEY \
            -DGPG_PASSPHRASE=$GPG_PASSPHRASE
