name: Publish to Sonatype

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew jreleaserPublish \
            -DSONATYPE_USERNAME=${{ secrets.GPG_PASSPHRASE }} \
            -DSONATYPE_PASSWORD=${{ secrets.GPG_PUBLIC_KEY }} \
            -DGPG_PUBLIC_KEY=$GPG_PUBLIC_KEY \
            -DGPG_SECRET_KEY=$GPG_SECRET_KEY \
            -DGPG_PASSPHRASE=$GPG_PASSPHRASE
